version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/effects"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/effects-core"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@galacean/effects-specification"

  - package-ecosystem: "npm"
    directory: "/packages/effects-helper"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/effects-threejs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "three"
      - dependency-name: "@types/three"

  - package-ecosystem: "npm"
    directory: "/packages/effects-webgl"
    schedule:
      interval: "weekly"
